name: Deploy

on:
  push:
    branches:
    - main
jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::674055165328:role/platform/ALZP-WL-Owner
          aws-region: us-east-1
      - name: deploy
        run: |          
          zip -j deploy.zip ./f_sharepoint_to_s3/*
          aws lambda update-function-code --function-name=s3-function --zip-file=fileb://deploy.zip
